'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Search, ChevronDown, ChevronUp, Eye, Edit, Trash2, XCircle, ArrowLeft, CheckCircle2, Plus, Settings2, Terminal } from 'lucide-react';
import { cn } from '@/lib/utils';

interface PipelineAction {
  id: string;
  name: string;
  initiatedBy: string;
  target: string;
  status: string;
  happenedAt: string;
}

interface Pipeline {
  id: string;
  notes: string;
  environment: string;
  rootWebDirectory: string;
  rootStorageDirectory: string;
  turnNginxContainerOff: boolean;
  enableRedisPrefixChange: boolean;
  deploymentPipeline: string;
  enableMaintenanceModeDb: boolean;
  tag: string;
  useCustomBuildCommands: boolean;
  customBuildCommands?: string;
  useCustomDatabaseCommands: boolean;
  useCustomPostBuildCommands: boolean;
  customPostBuildCommands?: string;
  reloadAdditionalDeployments: boolean;
  actions?: PipelineAction[];
}

const mockPipelines: Pipeline[] = [
  {
    id: '1502',
    notes: 'Deployment Pipeline for Magento 2 auto generated by Corefinity.',
    environment: 'Production',
    rootWebDirectory: '/var/www_m2/example.com/',
    rootStorageDirectory: '/var/www_m2/example.com/',
    turnNginxContainerOff: false,
    enableRedisPrefixChange: false,
    deploymentPipeline: 'Magento 2',
    enableMaintenanceModeDb: false,
    tag: '—',
    useCustomBuildCommands: true,
    customBuildCommands: `composer install --ignore-platform-reqs --no-dev --no-interaction --no-progress --prefer-dist --no-suggest
php bin/magento setup:upgrade --keep-generated
php bin/magento setup:di:compile
composer dump-autoload --no-ansi --no-scripts --no-interaction --optimize --apcu
php bin/magento setup:static-content:deploy en_GB en_US -f`,
    useCustomDatabaseCommands: false,
    useCustomPostBuildCommands: true,
    customPostBuildCommands: `php bin/magento cache:enable
php bin/magento cache:flush`,
    reloadAdditionalDeployments: false,
    actions: [
      { id: '116229', name: 'Update', initiatedBy: 'David Walsh', target: '-', status: 'Finished', happenedAt: '2026-04-07 14:57:51' },
      { id: '116228', name: 'Update', initiatedBy: 'David Walsh', target: '-', status: 'Finished', happenedAt: '2026-04-07 14:49:16' },
      { id: '115641', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:49:57' },
      { id: '115635', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:38:55' },
      { id: '115629', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:33:51' },
    ]
  }
];

interface PipelinesTabProps {
  environmentId: string;
}

export function PipelinesTab({ environmentId }: PipelinesTabProps) {
  const [pipelines, setPipelines] = useState<Pipeline[]>(mockPipelines);
  const [selectedPipelineId, setSelectedPipelineId] = useState<string | null>(null);

  const selectedPipeline = pipelines.find(p => p.id === selectedPipelineId);

  const SortIcon = () => (
    <div className="flex flex-col ml-1.5 opacity-50 group-hover:opacity-100 transition-opacity">
      <ChevronUp size={10} className="text-primary -mb-0.5" />
      <ChevronDown size={10} className="text-primary" />
    </div>
  );

  // Detail row component for consistent spacing
  const DetailRow = ({ 
    label, 
    children,
    highlight = false
  }: { 
    label: string; 
    children: React.ReactNode;
    highlight?: boolean;
  }) => (
    <div className="grid grid-cols-[280px_1fr] gap-6 items-center py-3.5 border-b border-border/30 last:border-b-0">
      <span className="text-sm text-muted-foreground">{label}</span>
      <div className={cn(highlight && "font-semibold text-primary")}>{children}</div>
    </div>
  );

  // Boolean indicator component
  const BooleanIndicator = ({ value }: { value: boolean }) => (
    value ? (
      <CheckCircle2 size={18} className="text-emerald-500" />
    ) : (
      <XCircle size={18} className="text-destructive/70" />
    )
  );

  if (selectedPipeline) {
    return (
      <div className="space-y-8 animate-in fade-in duration-300">
        {/* Header */}
        <div className="flex justify-between items-center pb-6 border-b border-border/50">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => setSelectedPipelineId(null)}
              className="flex items-center justify-center w-10 h-10 rounded-xl hover:bg-muted/50 text-muted-foreground hover:text-foreground transition-all duration-200"
            >
              <ArrowLeft size={20} />
            </button>
            <div>
              <h2 className="text-xl font-bold text-foreground tracking-tight">
                Pipeline Details
              </h2>
              <p className="text-sm text-muted-foreground mt-0.5">
                {selectedPipeline.deploymentPipeline} Deployment Pipeline
              </p>
            </div>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" size="icon" className="w-10 h-10 rounded-lg border-border/60 hover:bg-destructive/10 hover:text-destructive hover:border-destructive/30 transition-all duration-200">
              <Trash2 size={18} />
            </Button>
            <Button size="icon" className="w-10 h-10 rounded-lg bg-primary hover:bg-primary/90 transition-all duration-200">
              <Edit size={18} />
            </Button>
          </div>
        </div>

        {/* Pipeline Details Card */}
        <div className="bg-card/50 dark:bg-card/30 backdrop-blur-sm border border-border/50 rounded-xl p-6 space-y-1">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <Settings2 size={20} className="text-primary" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-foreground">Configuration</h3>
              <p className="text-sm text-muted-foreground">Pipeline settings and parameters</p>
            </div>
          </div>

          <DetailRow label="ID">
            <span className="text-sm font-mono text-foreground bg-muted/50 px-2.5 py-1 rounded-md">{selectedPipeline.id}</span>
          </DetailRow>

          <DetailRow label="Notes">
            <span className="text-sm text-foreground/80">{selectedPipeline.notes}</span>
          </DetailRow>

          <DetailRow label="Environment" highlight>
            <span className="text-sm px-3 py-1 rounded-full bg-primary/10 text-primary font-semibold">
              {selectedPipeline.environment}
            </span>
          </DetailRow>

          <DetailRow label="Root Web Directory">
            <span className="text-sm font-mono text-foreground/80 bg-muted/30 px-3 py-1.5 rounded-md">{selectedPipeline.rootWebDirectory}</span>
          </DetailRow>

          <DetailRow label="Root Storage Directory">
            <span className="text-sm font-mono text-foreground/80 bg-muted/30 px-3 py-1.5 rounded-md">{selectedPipeline.rootStorageDirectory}</span>
          </DetailRow>

          <DetailRow label="Turn Nginx Container Off">
            <BooleanIndicator value={selectedPipeline.turnNginxContainerOff} />
          </DetailRow>

          <DetailRow label="Enable Redis prefix change during build">
            <BooleanIndicator value={selectedPipeline.enableRedisPrefixChange} />
          </DetailRow>

          <DetailRow label="Deployment Pipeline" highlight>
            <span className="text-sm px-3 py-1 rounded-full bg-primary/10 text-primary font-semibold">
              {selectedPipeline.deploymentPipeline}
            </span>
          </DetailRow>

          <DetailRow label="Tag">
            <span className="text-sm text-muted-foreground">{selectedPipeline.tag}</span>
          </DetailRow>

          <DetailRow label="Use Custom Build Commands">
            <span className={cn(
              "text-sm font-medium",
              selectedPipeline.useCustomBuildCommands ? "text-emerald-500" : "text-muted-foreground"
            )}>
              {selectedPipeline.useCustomBuildCommands ? 'Yes' : 'No'}
            </span>
          </DetailRow>

          {selectedPipeline.customBuildCommands && (
            <div className="py-4 border-b border-border/30">
              <div className="flex items-center gap-2 mb-3">
                <Terminal size={16} className="text-primary" />
                <span className="text-sm font-medium text-foreground">Custom Build Commands</span>
              </div>
              <div className="bg-[#0d1117] dark:bg-[#0d1117] rounded-xl p-5 font-mono text-sm text-slate-300 overflow-x-auto border border-border/30">
                <pre className="leading-relaxed">
                  {selectedPipeline.customBuildCommands?.split('\n').map((line, i) => (
                    <div key={i} className="flex hover:bg-white/5 -mx-2 px-2 rounded transition-colors">
                      <span className="text-slate-500 mr-6 select-none w-5 text-right tabular-nums">{i + 1}</span>
                      <span className="text-emerald-400">{line}</span>
                    </div>
                  ))}
                </pre>
              </div>
            </div>
          )}

          <DetailRow label="Use Custom Database Commands">
            <span className={cn(
              "text-sm font-medium",
              selectedPipeline.useCustomDatabaseCommands ? "text-emerald-500" : "text-muted-foreground"
            )}>
              {selectedPipeline.useCustomDatabaseCommands ? 'Yes' : 'No'}
            </span>
          </DetailRow>

          <DetailRow label="Use Custom Post Build Commands">
            <span className={cn(
              "text-sm font-medium",
              selectedPipeline.useCustomPostBuildCommands ? "text-emerald-500" : "text-muted-foreground"
            )}>
              {selectedPipeline.useCustomPostBuildCommands ? 'Yes' : 'No'}
            </span>
          </DetailRow>

          {selectedPipeline.customPostBuildCommands && (
            <div className="py-4 border-b border-border/30">
              <div className="flex items-center gap-2 mb-3">
                <Terminal size={16} className="text-primary" />
                <span className="text-sm font-medium text-foreground">Custom Post Build Commands</span>
              </div>
              <div className="bg-[#0d1117] dark:bg-[#0d1117] rounded-xl p-5 font-mono text-sm text-slate-300 overflow-x-auto border border-border/30">
                <pre className="leading-relaxed">
                  {selectedPipeline.customPostBuildCommands?.split('\n').map((line, i) => (
                    <div key={i} className="flex hover:bg-white/5 -mx-2 px-2 rounded transition-colors">
                      <span className="text-slate-500 mr-6 select-none w-5 text-right tabular-nums">{i + 1}</span>
                      <span className="text-emerald-400">{line}</span>
                    </div>
                  ))}
                </pre>
              </div>
            </div>
          )}

          <DetailRow label="Reload additional deployments">
            <span className={cn(
              "text-sm font-medium",
              selectedPipeline.reloadAdditionalDeployments ? "text-emerald-500" : "text-muted-foreground"
            )}>
              {selectedPipeline.reloadAdditionalDeployments ? 'Yes' : 'No'}
            </span>
          </DetailRow>
        </div>

        {/* Actions Section */}
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <h3 className="text-lg font-semibold text-foreground tracking-tight">Actions History</h3>
            <span className="text-xs font-medium text-muted-foreground bg-muted/50 px-2.5 py-1 rounded-full">
              {selectedPipeline.actions?.length || 0} entries
            </span>
          </div>
          
          <div className="bg-card dark:bg-card/50 border border-border/50 rounded-xl overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-muted/30 dark:bg-muted/10 border-b border-border/50">
                <tr>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">ID</th>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">Name</th>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">Initiated By</th>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">Target</th>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">Status</th>
                  <th className="px-5 py-4 text-left font-semibold text-muted-foreground uppercase tracking-wider text-xs">Happened At</th>
                  <th className="px-5 py-4 w-12"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/30">
                {selectedPipeline.actions?.map((action) => (
                  <tr key={action.id} className="hover:bg-muted/20 dark:hover:bg-muted/10 transition-colors">
                    <td className="px-5 py-4 font-semibold text-foreground font-mono">{action.id}</td>
                    <td className="px-5 py-4 text-foreground/80">{action.name}</td>
                    <td className="px-5 py-4 text-foreground/80">{action.initiatedBy}</td>
                    <td className="px-5 py-4 text-muted-foreground">{action.target}</td>
                    <td className="px-5 py-4">
                      <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-500">
                        {action.status}
                      </span>
                    </td>
                    <td className="px-5 py-4 text-muted-foreground text-sm">{action.happenedAt}</td>
                    <td className="px-5 py-4">
                      <button className="p-2 rounded-lg hover:bg-muted/50 text-primary transition-colors">
                        <Eye size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          <div className="flex items-center justify-between text-sm px-1 pt-2">
            <button className="font-medium text-primary hover:text-primary/80 transition-colors">Previous</button>
            <span className="text-muted-foreground">1-5 of 9</span>
            <button className="font-medium text-primary hover:text-primary/80 transition-colors">Next</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-foreground tracking-tight">Pipelines</h2>
          <p className="text-sm text-muted-foreground mt-1">Manage deployment pipeline configurations</p>
        </div>
      </div>

      {/* Action Toolbar */}
      <div className="flex justify-between items-center gap-4">
        <div className="relative w-80">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={18} />
          <Input 
            placeholder="Search pipelines..." 
            className="pl-11 py-5 bg-card dark:bg-card/50 border-border/60 rounded-xl text-sm focus:ring-2 focus:ring-primary/20"
          />
        </div>
        
        <Button className="bg-primary hover:bg-primary/90 text-primary-foreground shadow-sm px-5 rounded-lg font-medium">
          <Plus size={18} className="mr-2" />
          Create Environment Deployment Pipeline
        </Button>
      </div>

      {/* Table */}
      <div className="bg-card dark:bg-card/50 border border-border/50 rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-sm whitespace-nowrap">
            <thead className="bg-muted/30 dark:bg-muted/10 border-b border-border/50">
              <tr>
                <th className="px-5 py-4 text-center w-12">
                  <input type="checkbox" className="w-4 h-4 rounded border-border accent-primary" />
                </th>
                <th className="px-5 py-4 text-left">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    ID <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-left min-w-[200px]">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    Notes <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-left">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    Environment <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-left">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    Root Web Dir <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-left">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    Root Storage Dir <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[80px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Nginx Off
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[90px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Redis Prefix
                  </div>
                </th>
                <th className="px-5 py-4 text-left">
                  <div className="flex items-center cursor-pointer group font-semibold text-muted-foreground uppercase tracking-wider text-xs">
                    Pipeline <SortIcon />
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[100px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Maintenance Mode
                  </div>
                </th>
                <th className="px-5 py-4 text-center font-semibold text-muted-foreground uppercase tracking-wider text-xs">Tag</th>
                <th className="px-5 py-4 text-center max-w-[80px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Custom Build
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[80px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Custom DB
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[80px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Post Build
                  </div>
                </th>
                <th className="px-5 py-4 text-center max-w-[80px]">
                  <div className="font-semibold text-muted-foreground uppercase tracking-wider text-xs whitespace-normal leading-tight">
                    Reload Deps
                  </div>
                </th>
                <th className="px-5 py-4 w-28"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/30">
              {pipelines.map((pipeline) => (
                <tr key={pipeline.id} className="hover:bg-muted/20 dark:hover:bg-muted/10 transition-colors">
                  <td className="px-5 py-4 text-center">
                    <input type="checkbox" className="w-4 h-4 rounded border-border accent-primary" />
                  </td>
                  <td className="px-5 py-4">
                    <button 
                      onClick={() => setSelectedPipelineId(pipeline.id)}
                      className="font-semibold text-primary hover:text-primary/80 hover:underline transition-colors"
                    >
                      {pipeline.id}
                    </button>
                  </td>
                  <td className="px-5 py-4 text-foreground/70 whitespace-normal min-w-[200px] max-w-[300px]">
                    <span className="line-clamp-2">{pipeline.notes}</span>
                  </td>
                  <td className="px-5 py-4">
                    <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-primary/10 text-primary">
                      {pipeline.environment}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <span className="text-foreground/70 font-mono text-xs">{pipeline.rootWebDirectory}</span>
                  </td>
                  <td className="px-5 py-4">
                    <span className="text-foreground/70 font-mono text-xs">{pipeline.rootStorageDirectory}</span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <BooleanIndicator value={pipeline.turnNginxContainerOff} />
                  </td>
                  <td className="px-5 py-4 text-center">
                    <BooleanIndicator value={pipeline.enableRedisPrefixChange} />
                  </td>
                  <td className="px-5 py-4">
                    <span className="font-semibold text-foreground">{pipeline.deploymentPipeline}</span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <BooleanIndicator value={pipeline.enableMaintenanceModeDb} />
                  </td>
                  <td className="px-5 py-4 text-center text-muted-foreground">
                    {pipeline.tag}
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className={cn(
                      "text-xs font-medium",
                      pipeline.useCustomBuildCommands ? "text-emerald-500" : "text-muted-foreground"
                    )}>
                      {pipeline.useCustomBuildCommands ? 'Yes' : 'No'}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className={cn(
                      "text-xs font-medium",
                      pipeline.useCustomDatabaseCommands ? "text-emerald-500" : "text-muted-foreground"
                    )}>
                      {pipeline.useCustomDatabaseCommands ? 'Yes' : 'No'}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className={cn(
                      "text-xs font-medium",
                      pipeline.useCustomPostBuildCommands ? "text-emerald-500" : "text-muted-foreground"
                    )}>
                      {pipeline.useCustomPostBuildCommands ? 'Yes' : 'No'}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className={cn(
                      "text-xs font-medium",
                      pipeline.reloadAdditionalDeployments ? "text-emerald-500" : "text-muted-foreground"
                    )}>
                      {pipeline.reloadAdditionalDeployments ? 'Yes' : 'No'}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <div className="flex items-center justify-end gap-1">
                      <button 
                        onClick={() => setSelectedPipelineId(pipeline.id)}
                        className="p-2 rounded-lg hover:bg-muted/50 text-primary transition-colors"
                      >
                        <Eye size={16} />
                      </button>
                      <button className="p-2 rounded-lg hover:bg-muted/50 text-muted-foreground hover:text-foreground transition-colors">
                        <Edit size={16} />
                      </button>
                      <button className="p-2 rounded-lg hover:bg-destructive/10 text-muted-foreground hover:text-destructive transition-colors">
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      
      {/* Pagination Footer */}
      <div className="flex items-center justify-between text-sm px-1">
        <button className="font-medium text-primary hover:text-primary/80 transition-colors">Previous</button>
        <span className="text-muted-foreground">1-1 of 1</span>
        <button className="font-medium text-primary hover:text-primary/80 transition-colors">Next</button>
      </div>
    </div>
  );
}
