'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Search, ChevronDown, ChevronUp, Eye, Edit, Trash2, XCircle, ArrowLeft } from 'lucide-react';

interface PipelineAction {
  id: string;
  name: string;
  initiatedBy: string;
  target: string;
  status: string;
  happenedAt: string;
}

interface Pipeline {
  id: string;
  notes: string;
  environment: string;
  rootWebDirectory: string;
  rootStorageDirectory: string;
  turnNginxContainerOff: boolean;
  enableRedisPrefixChange: boolean;
  deploymentPipeline: string;
  enableMaintenanceModeDb: boolean;
  tag: string;
  useCustomBuildCommands: boolean;
  customBuildCommands?: string;
  useCustomDatabaseCommands: boolean;
  useCustomPostBuildCommands: boolean;
  customPostBuildCommands?: string;
  reloadAdditionalDeployments: boolean;
  actions?: PipelineAction[];
}

const mockPipelines: Pipeline[] = [
  {
    id: '1502',
    notes: 'Deployment Pipeline for Magento 2 auto generated by Corefinity.',
    environment: 'Production',
    rootWebDirectory: '/var/www_m2/example.com/',
    rootStorageDirectory: '/var/www_m2/example.com/',
    turnNginxContainerOff: false,
    enableRedisPrefixChange: false,
    deploymentPipeline: 'Magento 2',
    enableMaintenanceModeDb: false,
    tag: '—',
    useCustomBuildCommands: true,
    customBuildCommands: `composer install --ignore-platform-reqs --no-dev --no-interaction --no-progress --prefer-dist --no-suggest
php bin/magento setup:upgrade --keep-generated
php bin/magento setup:di:compile
composer dump-autoload --no-ansi --no-scripts --no-interaction --optimize --apcu
php bin/magento setup:static-content:deploy en_GB en_US -f`,
    useCustomDatabaseCommands: false,
    useCustomPostBuildCommands: true,
    customPostBuildCommands: `php bin/magento cache:enable
php bin/magento cache:flush`,
    reloadAdditionalDeployments: false,
    actions: [
      { id: '116229', name: 'Update', initiatedBy: 'David Walsh', target: '-', status: 'Finished', happenedAt: '2026-04-07 14:57:51' },
      { id: '116228', name: 'Update', initiatedBy: 'David Walsh', target: '-', status: 'Finished', happenedAt: '2026-04-07 14:49:16' },
      { id: '115641', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:49:57' },
      { id: '115635', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:38:55' },
      { id: '115629', name: 'Update', initiatedBy: 'Adam Preece', target: '-', status: 'Finished', happenedAt: '2026-03-31 09:33:51' },
    ]
  }
];

interface PipelinesTabProps {
  environmentId: string;
}

export function PipelinesTab({ environmentId }: PipelinesTabProps) {
  const [pipelines, setPipelines] = useState<Pipeline[]>(mockPipelines);
  const [selectedPipelineId, setSelectedPipelineId] = useState<string | null>(null);

  const selectedPipeline = pipelines.find(p => p.id === selectedPipelineId);

  const SortIcon = () => (
    <div className="flex flex-col ml-1">
      <ChevronUp size={10} className="text-[#2fa4c7] -mb-[2px]" />
      <ChevronDown size={10} className="text-[#2fa4c7]" />
    </div>
  );

  if (selectedPipeline) {
    return (
      <div className="space-y-8 animate-in fade-in duration-300">
        <div className="flex justify-between items-center mb-6 border-b border-[#dcecf1] pb-4">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => setSelectedPipelineId(null)}
              className="flex items-center justify-center p-2 rounded-full hover:bg-muted text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft size={20} />
            </button>
            <h2 className="text-xl font-bold text-[#1f4a76]">
              Environment Deployment Pipeline Details: {selectedPipeline.deploymentPipeline} Deployment Pipeline
            </h2>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="icon" className="border-[#dcecf1] text-[#2e5e7e] hover:bg-[#f0f8fa]">
              <Trash2 size={16} />
            </Button>
            <Button size="icon" className="bg-[#ff6b2a] hover:bg-[#e95a1c] border-none text-white">
              <Edit size={16} />
            </Button>
          </div>
        </div>

        <div className="space-y-5 px-2">
          {/* Info Rows */}
          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">ID</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.id}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Notes</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.notes}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Environment</span>
            <span className="text-[13px] font-bold text-[#ff6b2a]">{selectedPipeline.environment}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Root Web Directory</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.rootWebDirectory}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Root Storage Directory</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.rootStorageDirectory}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Turn Nginx Container Off</span>
            {!selectedPipeline.turnNginxContainerOff && (
              <XCircle size={16} className="text-red-500" />
            )}
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Enable Redis prefix change during build</span>
            {!selectedPipeline.enableRedisPrefixChange && (
              <XCircle size={16} className="text-red-500" />
            )}
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Deployment Pipeline</span>
            <span className="text-[13px] font-bold text-[#ff6b2a]">{selectedPipeline.deploymentPipeline}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Tag</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.tag}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Use Custom Build Commands</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.useCustomBuildCommands ? 'Yes' : 'No'}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-start pt-2">
            <span className="text-[13px] font-medium text-[#2e5e7e] mt-2">Custom Build Commands</span>
            <div className="bg-[#1e293b] rounded-lg p-4 font-mono text-[13px] text-gray-300 overflow-x-auto shadow-sm border border-border/50">
              <pre className="leading-relaxed">
                {selectedPipeline.customBuildCommands?.split('\n').map((line, i) => (
                  <div key={i} className="flex">
                    <span className="text-gray-500 mr-4 select-none w-4 text-right">{i + 1}</span>
                    <span>{line}</span>
                  </div>
                ))}
              </pre>
            </div>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center pt-2">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Use Custom Database Commands</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.useCustomDatabaseCommands ? 'Yes' : 'No'}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Use Custom Post Build Commands</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.useCustomPostBuildCommands ? 'Yes' : 'No'}</span>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-start pt-2">
            <span className="text-[13px] font-medium text-[#2e5e7e] mt-2">Custom Post Build Commands</span>
            <div className="bg-[#1e293b] rounded-lg p-4 font-mono text-[13px] text-gray-300 overflow-x-auto shadow-sm border border-border/50">
              <pre className="leading-relaxed">
                {selectedPipeline.customPostBuildCommands?.split('\n').map((line, i) => (
                  <div key={i} className="flex">
                    <span className="text-gray-500 mr-4 select-none w-4 text-right">{i + 1}</span>
                    <span>{line}</span>
                  </div>
                ))}
              </pre>
            </div>
          </div>

          <div className="grid grid-cols-[250px_1fr] gap-4 items-center pt-2">
            <span className="text-[13px] font-medium text-[#2e5e7e]">Reload additional deployments</span>
            <span className="text-[13px] text-[#1f4a76]">{selectedPipeline.reloadAdditionalDeployments ? 'Yes' : 'No'}</span>
          </div>
        </div>

        {/* Actions Section */}
        <div className="mt-12">
          <h3 className="text-lg font-bold text-[#2fa4c7] mb-4 border-b border-[#dcecf1] pb-2">Actions</h3>
          
          <div className="bg-white border-y border-[#dcecf1]">
            <table className="w-full text-xs">
              <thead className="bg-[#f0f8fa]">
                <tr>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">ID</th>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">Name</th>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">Initiated By</th>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">Target</th>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">Status</th>
                  <th className="px-4 py-3 text-left font-bold text-[#1f4a76] uppercase tracking-wider">Happened At</th>
                  <th className="px-4 py-3 text-right"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#dcecf1]">
                {selectedPipeline.actions?.map((action) => (
                  <tr key={action.id} className="hover:bg-[#f0f8fa]/50 transition-colors">
                    <td className="px-4 py-4 font-bold text-[#1f4a76]">{action.id}</td>
                    <td className="px-4 py-4 text-[#5da2c3]">{action.name}</td>
                    <td className="px-4 py-4 text-[#5da2c3]">{action.initiatedBy}</td>
                    <td className="px-4 py-4 text-[#5da2c3]">{action.target}</td>
                    <td className="px-4 py-4 text-[#5da2c3]">{action.status}</td>
                    <td className="px-4 py-4 text-[#5da2c3]">{action.happenedAt}</td>
                    <td className="px-4 py-4 text-right">
                      <Eye size={16} className="inline-block cursor-pointer text-[#2fa4c7] hover:text-[#1f4a76] transition-colors" />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          <div className="flex items-center justify-between text-xs text-[#ff6b2a] px-2 pt-3 font-medium">
            <span className="cursor-pointer hover:text-[#e95a1c]">Previous</span>
            <span className="text-[#5da2c3]">1-5 of 9</span>
            <span className="cursor-pointer hover:text-[#e95a1c]">Next</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-[28px] font-bold text-[#1f4a76]">Pipelines</h2>
        </div>
      </div>

      {/* Action Toolbar */}
      <div className="relative mb-2">
        <div className="flex justify-between items-start mb-4">
          <div className="relative w-80">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#2fa4c7]" size={18} />
            <Input 
              placeholder="Search" 
              className="pl-10 py-5 bg-white border-[#dcecf1] rounded-full text-sm shadow-sm placeholder:text-muted-foreground/60 focus-visible:ring-[#2fa4c7]"
            />
          </div>
          
          <div className="flex flex-col items-end gap-3">
            <Button
              className="bg-[#ff6b2a] hover:bg-[#e95a1c] text-white font-medium border-none px-5 rounded"
            >
              Create Environment Deployment Pipeline
            </Button>
          </div>
        </div>

        <div className="flex items-center gap-2 mb-2 ml-4">
          <input type="checkbox" className="w-[18px] h-[18px] rounded border-[#2fa4c7] text-[#2fa4c7] focus:ring-[#2fa4c7]" />
          <ChevronDown size={18} className="text-[#1f4a76] cursor-pointer" />
        </div>
      </div>

      <div className="bg-card border border-[#dcecf1] rounded-lg overflow-hidden shadow-card mt-2">
        <div className="overflow-x-auto">
          <table className="w-full text-[11px] whitespace-nowrap">
            <thead className="bg-[#f0f8fa] border-b border-[#dcecf1]">
              <tr>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider w-10">
                  <input type="checkbox" className="w-[18px] h-[18px] rounded border-[#2fa4c7]" />
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider">
                  <div className="flex items-center justify-start cursor-pointer">ID <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider min-w-[200px]">
                  <div className="flex items-center justify-start cursor-pointer">NOTES <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider">
                  <div className="flex items-center justify-start cursor-pointer">ENVIRONMENT <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider">
                  <div className="flex items-center justify-start cursor-pointer">ROOT WEB DIRECTORY <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider">
                  <div className="flex items-center justify-start cursor-pointer">ROOT STORAGE DIRECTORY <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[80px] whitespace-normal leading-tight">
                  <div className="flex items-center justify-center">TURN NGINX CONTAINER OFF</div>
                </th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[90px] whitespace-normal leading-tight">
                  <div className="flex items-center justify-center">ENABLE REDIS PREFIX CHANGE DURING BUILD</div>
                </th>
                <th className="px-4 py-4 text-left font-bold text-[#1f4a76] uppercase tracking-wider">
                  <div className="flex items-center justify-start cursor-pointer">DEPLOYMENT PIPELINE <SortIcon /></div>
                </th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[100px] whitespace-normal leading-tight">
                  <div className="flex items-center justify-center cursor-pointer">ENABLE MAINTENANCE MODE DURING DATABASE COMMANDS</div>
                </th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider">TAG</th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[80px] whitespace-normal leading-tight">USE CUSTOM BUILD COMMANDS</th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[80px] whitespace-normal leading-tight">USE CUSTOM DATABASE COMMANDS</th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[80px] whitespace-normal leading-tight">USE CUSTOM POST BUILD COMMANDS</th>
                <th className="px-4 py-4 text-center font-bold text-[#1f4a76] uppercase tracking-wider max-w-[80px] whitespace-normal leading-tight">RELOAD ADDITIONAL DEPLOYMENTS</th>
                <th className="px-4 py-4"></th> {/* Actions */}
              </tr>
            </thead>
            <tbody className="divide-y divide-[#dcecf1]">
              {pipelines.map((pipeline) => (
                <tr key={pipeline.id} className="hover:bg-[#f0f8fa]/50 transition-colors">
                  <td className="px-4 py-5 text-center">
                    <input type="checkbox" className="w-[18px] h-[18px] rounded border-[#2fa4c7]" />
                  </td>
                  <td className="px-4 py-5 text-left font-bold text-[#1f4a76] cursor-pointer hover:underline" onClick={() => setSelectedPipelineId(pipeline.id)}>
                    {pipeline.id}
                  </td>
                  <td className="px-4 py-5 text-left text-muted-foreground whitespace-normal min-w-[200px]">
                    {pipeline.notes}
                  </td>
                  <td className="px-4 py-5 text-left font-bold text-[#1f4a76]">
                    {pipeline.environment}
                  </td>
                  <td className="px-4 py-5 text-left text-[#5da2c3]">
                    {pipeline.rootWebDirectory}
                  </td>
                  <td className="px-4 py-5 text-left text-[#5da2c3]">
                    {pipeline.rootStorageDirectory}
                  </td>
                  <td className="px-4 py-5 text-center">
                    {!pipeline.turnNginxContainerOff && (
                      <XCircle size={16} className="text-red-500 mx-auto" />
                    )}
                  </td>
                  <td className="px-4 py-5 text-center">
                    {!pipeline.enableRedisPrefixChange && (
                      <XCircle size={16} className="text-red-500 mx-auto" />
                    )}
                  </td>
                  <td className="px-4 py-5 text-left font-bold text-[#1f4a76]">
                    {pipeline.deploymentPipeline}
                  </td>
                  <td className="px-4 py-5 text-center">
                    {!pipeline.enableMaintenanceModeDb && (
                      <XCircle size={16} className="text-red-500 mx-auto" />
                    )}
                  </td>
                  <td className="px-4 py-5 text-center text-[#5da2c3]">
                    {pipeline.tag}
                  </td>
                  <td className="px-4 py-5 text-center text-[#5da2c3]">
                    {pipeline.useCustomBuildCommands ? 'Yes' : 'No'}
                  </td>
                  <td className="px-4 py-5 text-center text-[#5da2c3]">
                    {pipeline.useCustomDatabaseCommands ? 'Yes' : 'No'}
                  </td>
                  <td className="px-4 py-5 text-center text-[#5da2c3]">
                    {pipeline.useCustomPostBuildCommands ? 'Yes' : 'No'}
                  </td>
                  <td className="px-4 py-5 text-center text-[#5da2c3]">
                    {pipeline.reloadAdditionalDeployments ? 'Yes' : 'No'}
                  </td>
                  <td className="px-4 py-5 text-right">
                    <div className="flex items-center justify-end gap-3 text-[#2fa4c7]">
                      <Eye size={18} className="cursor-pointer hover:text-[#1f4a76] transition-colors" onClick={() => setSelectedPipelineId(pipeline.id)} />
                      <Edit size={18} className="cursor-pointer hover:text-[#1f4a76] transition-colors" />
                      <Trash2 size={18} className="cursor-pointer hover:text-red-600 transition-colors" />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      
      {/* Pagination Footer */}
      <div className="flex items-center justify-between text-xs text-[#5da2c3] px-2 pt-2">
        <span className="font-medium cursor-pointer hover:text-[#2fa4c7]">Previous</span>
        <span>1-1 of 1</span>
        <span className="font-medium cursor-pointer hover:text-[#2fa4c7]">Next</span>
      </div>
    </div>
  );
}
